services:
  db:
    image: postgres:15
    container_name: personal-web-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d portfolio"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: personal-web-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/portfolio?schema=public"
      JWT_SECRET: "clave-secreta-docker"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: personal-web-frontend
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3000"
    depends_on:
      - backend

volumes:
  postgres_data: